title: GO 4 OOP Devs
description: Documentation for the OOP Devs that are starting to work with GO
theme: "just-the-docs"

enable_dark_mode: true
color_scheme: dark

just_the_docs:
  sidebar:
    navigation: "_sidebar.md"
